"""PROJECT.md / control-plane file generation.

Byte-parity contract with New-Project.ps1 (the PS1 tools stay alive until P4,
and Norma + PRD-209's identity chain parse these files): UTF-8 with NO BOM,
CRLF line endings, trailing newline, identical line content - with exactly two
sanctioned divergences, both asserted by the golden test:

1. Attribution line says "Generated by Atlas." (not "Generated by New-Project.").
2. The canonical-map section is wrapped in <!-- atlas:map-begin/end --> markers
   so Doctor --fix-project-md can regenerate it idempotently (spec 5.6).
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from .mapfile import DriveMap

MAP_BEGIN = "<!-- atlas:map-begin -->"
MAP_END = "<!-- atlas:map-end -->"

# The machine contract - identical in New-Project.ps1 and Conform-Project.ps1.
# Bare keys, no inline comments (a tiny YAML fallback parser reads comments as
# values), and never a BOM ahead of the opening '---'.
FRONT_MATTER_HEAD = (
    "---",
    "# Machine contract - tool-authoritative project facts. Norma and other",
    "# architect skills read THIS YAML block, not the prose below. A blank field",
    "# is ignored, not assumed; Norma adopts this project only once jurisdiction /",
    "# occupancy_group / edition are real. Run /project-dossier to fill it in, and",
    "# keep it in sync with the Identity + Code tables (the human mirror).",
)
FRONT_MATTER_KEYS = (
    "address:",
    "jurisdiction:",
    "edition:",
    "occupancy_group:",
    "construction_type:",
    "sprinklered:",
    "stories:",
    "building_area_sf:",
    "frontage_ft:",
    "existing_co_occupant_load:",
    "existing_exits:",
    "place_of_assembly_strategy:",
    "tenancy:",
    "---",
)


def write_crlf_no_bom(path: Path, lines: list[str]) -> None:
    """The PS1 writer's exact byte behavior: WriteAllLines = line + CRLF each."""
    data = ("\r\n".join(lines) + "\r\n").encode("utf-8")
    path.write_bytes(data)


def project_md_lines(m: DriveMap, folder_name: str, name: str, desc: str, created: date) -> list[str]:
    lines: list[str] = []
    lines += FRONT_MATTER_HEAD
    lines.append(f'project: "{name}"')
    lines += FRONT_MATTER_KEYS
    lines += [
        "",
        f"# {folder_name}",
        "",
        "> Maintained by Architecture Studio skills and the project team. Facts only -",
        "> rationale lives in `decisions/`. The YAML front-matter above is the machine",
        "> mirror of the Identity + Code tables; keep them in agreement.",
        "> **Next:** run `/project-dossier` to fill in the project facts.",
        "",
        "## Identity",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Project | {name} |",
        "| Address / BBL | |",
        "| Client | |",
        "| Jurisdiction | |",
        f"| Descriptor | {desc} |",
        f"| Created | {created.strftime('%Y-%m-%d')} |",
        f"| Drive | {m.drive} |",
        "| Status | Active |",
        "",
        "## Site",
        "",
        "<!-- site-planner skills append here: climate, flood, transit, demographics, context -->",
        "",
        "## Zoning",
        "",
        "<!-- zoning skills append here: district, FAR, envelope, overlays, landmark status -->",
        "",
        "## Program",
        "",
        "<!-- programming skills append here: headcount, space program, occupant loads -->",
        "",
        "## Code",
        "",
        "<!-- Mirrors the machine contract in the front-matter. Change a value here -> change it there too. -->",
        "",
        "| Item | Value | Source | Date |",
        "|------|-------|--------|------|",
        "| Building code edition | | | |",
        "| Occupancy group | | | |",
        "| Construction type | | | |",
        "| Sprinklered | | | |",
        "| Stories | | | |",
        "| Building area (SF) | | | |",
        "| Frontage (ft) | | | |",
        "| Existing C-of-O occupant load | | | |",
        "| Existing exits | | | |",
        "| Place-of-assembly strategy | | | |",
        "| Tenancy | | | |",
        "",
        "## Decisions",
        "",
        "<!-- maintained by /decision - do not edit by hand -->",
        "",
        "| # | Decision | Status | Date |",
        "|---|----------|--------|------|",
        "",
    ]
    lines += canonical_map_lines(m)
    return lines


def canonical_map_lines(m: DriveMap) -> list[str]:
    """The regenerable 'Where things go' block, marker-wrapped for --fix-project-md."""
    lines = [
        MAP_BEGIN,
        "## Where things go (canonical map)",
        "",
        "Sections tagged **[seed]** exist now. Everything else is created on demand:",
        "double-click `_tools\\Add-Section.bat`, pick this project, pick the folder.",
        "**Do not hand-create canonical folders** - use Add-Section so names never drift.",
        "",
    ]
    for section in m.sections:
        tag = " _[seed]_" if section.seed else " _[on demand]_"
        lines.append(f"- **{section.id}**{tag}")
        for child in section.children:
            lines.append(f"  - {child}")
    lines += [
        "",
        f"_Naming: {m.project_naming}. Generated by Atlas._",
        MAP_END,
    ]
    return lines


def decisions_readme_lines() -> list[str]:
    return [
        "# Decisions",
        "",
        "ADR-style decision records for this project - one per file (`NNNN-slug.md`),",
        "maintained by the `/decision` skill. Rationale lives here; current facts live",
        "in `../PROJECT.md`.",
    ]


def claude_md_lines(m: DriveMap) -> list[str]:
    return [
        "# Architecture project workspace",
        "",
        "Project facts live in `PROJECT.md` (the YAML machine contract every architect",
        "skill reads - most importantly Norma, which scopes code answers from it).",
        "Decisions live in `decisions/`. Norma writes cited code analyses to",
        f"`{m.analysis_dir}`.",
        "",
        "Start with `/project-dossier` to fill in `PROJECT.md`, then run `/code-analysis`,",
        "`/egress`, `/ibc`, etc. from this folder.",
    ]
