from __future__ import annotations

from datetime import date

import pytest

from atlas.core.doctor import report_drive
from atlas.core.mapfile import find_map, load_map
from atlas.core.naming import build_folder_name, clean_name_part
from atlas.core.ops import OpsError, add_sections, find_empty_dirs, new_project, remove_empty_dirs
from atlas.core.scan import scan_drive

CREATED = date(2026, 8, 13)


def load(fixture_drive):
    return load_map(find_map(fixture_drive))


# ------------------------------------------------------------------ naming

def test_clean_name_part_ps1_parity():
    assert clean_name_part('  a/b:c*d?e"f<g>h|i  ') == "a b c d e f g h i"
    assert clean_name_part("Two   Spaces") == "Two Spaces"
    assert clean_name_part("Trailing dot.") == "Trailing dot"
    assert clean_name_part(None) == ""


def test_build_folder_name():
    assert build_folder_name(CREATED, "House") == "260813_House"
    assert build_folder_name(CREATED, "House", "ADU") == "260813_House-ADU"


# ------------------------------------------------------------------ new

def test_new_project_creates_seeds_and_control_plane(fixture_drive):
    m = load(fixture_drive)
    result = new_project(fixture_drive, m, "Test House", "ADU", created=CREATED)
    p = result.path
    assert result.folder_name == "260813_Test House-ADU"
    assert (p / "01 Model").is_dir()
    assert (p / "11 Meetings").is_dir()
    assert not (p / "10 Legal").exists()  # seed=false stays JIT
    assert not any((p / "01 Model").iterdir())  # seed children NOT created (PS1 parity)
    assert (p / "PROJECT.md").is_file()
    assert (p / "decisions" / "README.md").is_file()
    assert (p / "CLAUDE.md").is_file()
    assert (p / "06 Research" / "Code").is_dir()
    index = (fixture_drive / "_Project Index.md").read_bytes().decode("utf-8")
    assert "| 260813_Test House-ADU | 2026-08-13 | ADU | Active |" in index


def test_new_project_refuses_existing(fixture_drive):
    m = load(fixture_drive)
    new_project(fixture_drive, m, "Twice", created=CREATED)
    with pytest.raises(OpsError, match="already exists"):
        new_project(fixture_drive, m, "Twice", created=CREATED)


def test_new_project_is_doctor_conform(fixture_drive):
    # The P2 gate tying into P1: a freshly created project must report CONFORM.
    m = load(fixture_drive)
    new_project(fixture_drive, m, "Fresh", "New", created=CREATED)
    report = report_drive(scan_drive(fixture_drive))
    (p,) = [x for x in report.projects if x.name == "260813_Fresh-New"]
    assert p.status == "conform", (p.missing_control_plane, p.unfiled, p.drift)


def test_project_md_bytes(fixture_drive):
    """Byte-level contract: UTF-8 no BOM, CRLF, trailing newline, front matter
    first, and the two sanctioned divergences from New-Project.ps1 output."""
    m = load(fixture_drive)
    result = new_project(fixture_drive, m, "Golden", "Spec", created=CREATED)
    raw = (result.path / "PROJECT.md").read_bytes()
    assert not raw.startswith(b"\xef\xbb\xbf")           # no BOM, Norma requirement
    assert raw.startswith(b"---\r\n")                      # front matter first, CRLF
    assert raw.endswith(b"\r\n")                           # trailing newline
    assert b"\n" not in raw.replace(b"\r\n", b"")          # CRLF-only line endings

    text = raw.decode("utf-8")
    lines = text.split("\r\n")
    # Machine contract exactly as the PS1 tools write it.
    assert 'project: "Golden"' in lines
    assert "tenancy:" in lines
    assert lines.index("---", 1) > lines.index('project: "Golden"')
    # Identity mirrors New-Project (Descriptor/Created/Drive/Status rows).
    for row in ("| Project | Golden |", "| Descriptor | Spec |",
                "| Created | 2026-08-13 |", "| Drive | TESTDRIVE |", "| Status | Active |"):
        assert row in lines, row
    # Canonical map block present, marker-wrapped (sanctioned divergence 2).
    assert "<!-- atlas:map-begin -->" in lines
    assert "<!-- atlas:map-end -->" in lines
    assert "- **01 Model** _[seed]_" in lines
    assert "- **10 Legal** _[on demand]_" in lines
    assert "  - Invoices" in lines
    # Attribution (sanctioned divergence 1).
    assert "_Naming: YYMMDD_<Name>-<Descriptor>. Generated by Atlas._" in lines
    assert "Generated by New-Project" not in text


# ------------------------------------------------------------------ add

def test_add_sections_blessed_only(fixture_drive):
    m = load(fixture_drive)
    result = new_project(fixture_drive, m, "Adder", created=CREATED)
    created = add_sections(fixture_drive, m, result.path, ["10 Legal", "10 Legal/Invoices"])
    assert created == ["10 Legal", "10 Legal/Invoices"]
    assert (result.path / "10 Legal" / "Invoices").is_dir()
    # idempotent
    assert add_sections(fixture_drive, m, result.path, ["10 Legal"]) == []


def test_add_sections_rejects_unblessed(fixture_drive):
    m = load(fixture_drive)
    result = new_project(fixture_drive, m, "Strict", created=CREATED)
    with pytest.raises(OpsError, match="not a blessed child"):
        add_sections(fixture_drive, m, result.path, ["10 Legal/Random Folder"])
    with pytest.raises(OpsError, match="not a canonical section"):
        add_sections(fixture_drive, m, result.path, ["Random Section"])


# ------------------------------------------------------------------ clean

def test_clean_finds_and_removes_empty_chains(fixture_drive):
    m = load(fixture_drive)
    result = new_project(fixture_drive, m, "Cleaner", created=CREATED)
    p = result.path
    (p / "10 Legal" / "Invoices").mkdir(parents=True)          # empty chain
    (p / "08 OUT" / "RFI").mkdir()
    (p / "08 OUT" / "RFI" / "r1.pdf").write_text("x")           # has a file

    empties = find_empty_dirs(p, m)
    assert "10 Legal/Invoices" in empties and "10 Legal" in empties
    assert "08 OUT/RFI" not in empties
    assert "decisions" not in empties                            # protected
    assert "01 Model" not in empties                             # seed top kept by default

    removed = remove_empty_dirs(fixture_drive, p, empties)
    assert not (p / "10 Legal").exists()
    assert (p / "08 OUT" / "RFI" / "r1.pdf").exists()
    assert set(removed) == set(empties)


def test_clean_include_seeds_removes_empty_seed_tops(fixture_drive):
    m = load(fixture_drive)
    result = new_project(fixture_drive, m, "Seedless", created=CREATED)
    empties = find_empty_dirs(result.path, m, include_seeds=True)
    assert "01 Model" in empties and "11 Meetings" in empties
    # analysisDir is control plane: never removable, and it anchors its section.
    assert "06 Research/Code" not in empties
    assert "06 Research" not in empties


def test_clean_default_on_fresh_project_is_noop(fixture_drive):
    m = load(fixture_drive)
    result = new_project(fixture_drive, m, "Pristine", created=CREATED)
    assert find_empty_dirs(result.path, m) == []